-- Kansari Restaurant — Seed data
-- Run this once (after schema.sql) in the Supabase SQL Editor.

-- Admin user (password: nayeem@131, bcrypt-hashed by the app on first write —
-- here we insert a pre-hashed value generated the same way the app does it)
-- NOTE: this INSERT is executed separately by the app on first boot if the row
-- is missing, so you can also skip this block; included for completeness.

insert into categories (id, name, bengali_name, sub_label, sort_order, is_visible) values
  ('cat-starters', 'STARTERS', 'শুরুর পদ ও কাবাব', 'Starters & Kababs', 1, true),
  ('cat-specials', 'KANSARI SPECIALS', 'কাঁসারী স্পেশাল', 'Chef''s Signatures', 2, true),
  ('cat-biryani', 'BHAAT & BIRYANI', 'ভাত ও বিরিয়ানি', 'Rice & Biryani', 3, true),
  ('cat-fish', 'FISH', 'মাছের সমাহার', 'Padma & River Fish', 4, true),
  ('cat-meat', 'MEAT', 'মাংসের পদ', 'Mutton, Beef & Poultry', 5, true),
  ('cat-veg', 'VEGETARIAN', 'ভর্তা ও নিরামিষ', 'Bhorta & Veggies', 6, true),
  ('cat-drinks', 'DRINKS', 'শরবত ও পানীয়', 'Borhani & Refreshers', 7, true),
  ('cat-desserts', 'DESSERTS', 'মিষ্টান্ন ও দই', 'Doi & Traditional Sweets', 8, true)
on conflict (id) do nothing;

insert into menu_items (id, category_id, name, bengali_name, price, description, bengali_description, image, tag, badge, featured, available, sort_order) values
  ('item-1', 'cat-specials', 'Grand Kansari Mutton Kacchi', 'গ্র্যান্ড কাঁসারী খাসির কাচ্চি', '৳৫৮০', 'Slow-cooked tender mutton layered with aromatic chinigura rice, aloo bukhara, saffron, and pure ghee in sealed degchi.', '১২ ঘণ্টার ধীর আঁচে দম দেওয়া—ঘিয়ে ভাজা আলু, জাফরান চাল আর নরম তুলতুলে খাসির মাংসের অবিস্মরণীয় মেলবন্ধন।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/grand-kansari-mutton-kacchi.jpg', 'SIGNATURE MASTERPIECE', 'জনপ্রিয় সেরা', true, true, 1),
  ('item-2', 'cat-specials', 'Authentic Chittagong Kala Bhuna', 'চট্টগ্রামের সনাতন কালাভুনা', '৳৫৬০', 'Prime beef slow-roasted in cast iron with mustard oil, dried red chillies, and 18 aromatic whole roasted spices.', 'ঘণ্টার পর ঘণ্টা কষানো কুচকুচে কালো মাংসের খাঁটি ঐতিহ্যবাহী মসলাদার স্বাদ ও তীব্র সুবাস।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/authentic-chittagong-kala-bhuna.jpg', 'SLOW BRAISED', 'সনাতন ঐতিহ্য', true, true, 2),
  ('item-3', 'cat-fish', 'Padma River Shorshe Ilish', 'পদ্মার তাজা ভাপা সরিষা ইলিশ', '৳৯৫০', 'Fresh Padma River Hilsa fish steamed with stone-ground yellow mustard paste, green chilies, and virgin mustard oil.', 'শিল-পাটায় বাটা ঝাঁঝালো সরিষা বাটা ও কাঁচামরিচে ভাপানো পদ্মার রূপালী ইলিশের রাজকীয় স্বাদ।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/padma-river-shorshe-ilish.jpg', 'PADMA SPECIAL', 'পদ্মার তাজা ইলিশ', true, true, 3),
  ('item-4', 'cat-meat', 'Biyer Barir Shahi Chicken Roast', 'বিয়ের বাড়ির শাহি চিকেন রোস্ট', '৳৩৯০', 'Quarter chicken leg cooked in a rich, mild yogurt, cashew, and mawa gravy with fried golden onions.', 'খাঁটি গাওয়া ঘি, টকদই, বাদাম বাটা আর বেরেস্তার মিষ্টি সোনালী গ্রেভিতে ডুবানো দেশি মুরগির রোস্ট।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/biyer-barir-shahi-chicken-roast.jpg', 'HOUSE FAVORITE', 'বিয়ে বাড়ির স্বাদ', true, true, 4),
  ('item-5', 'cat-biryani', 'Puran Dhaka Shorshe Beef Tehari', 'পুরান ঢাকার সরিষার তেলের বিফ তেহারি', '৳৩৯০', 'Aromatic chinigura rice and tender beef cubes cooked together in pure mustard oil and green chillies.', 'ঝাঁঝালো সরিষার তেলে সুগন্ধি চিনিগুঁড়া চাল ও নরম গরুর মাংসের টুকরো দিয়ে রান্না করা আসল ঢাকাই তেহারি।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/puran-dhaka-shorshe-beef-tehari.jpg', 'MUSTARD OIL', 'ঢাকাই ঐতিহ্য', false, true, 5),
  ('item-6', 'cat-fish', 'Golda Chingri Malai Curry', 'গলদা চিংড়ির মালাইকারি', '৳৬৮০', 'Jumbo fresh-water tiger prawns braised in thick creamy coconut milk, mild spices, and ghee.', 'ঘন নারিকেলের দুধ, খাঁটি ঘি আর মিষ্টি মসলার রাজকীয় মালাই গ্রেভিতে তৈরি জাম্বো গলদা চিংড়ি।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/golda-chingri-malai-curry.jpg', 'CREAMY DELIGHT', 'রাজকীয় পদ', false, true, 6),
  ('item-7', 'cat-meat', 'Royal Mughlai Mutton Rezala', 'শাহী মোঘলাই মাটন রেজালা', '৳৫৬০', 'Tender goat meat cooked in silky white gravy of poppy seed paste, yogurt, kewra water, and makhana.', 'পোস্ত বাটা, টকদই, জয়ত্রী আর কেওড়ার সুবাসিত সাদা গ্রেভিতে রান্না করা নরম তুলতুলে খাসির রেজালা।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/royal-mughlai-mutton-rezala.jpg', 'ROYAL GRAVY', 'মোঘলাই রেসিপি', false, true, 7),
  ('item-8', 'cat-biryani', 'Bhuna Khichuri with Beef Kosha', 'ভুনা খিচুড়ি সাথে বিফ কষা', '৳৪৩০', 'Yellow moong dal and chinigura rice slow-cooked with ghee, paired with tender rich beef kosha.', 'ঘিয়ে ভাজা সোনা মুগ ডাল ও সুগন্ধি চালের ঝরঝরে খিচুড়ির সাথে মুখে মিলিয়ে যাওয়া ঝাল গরুর মাংস।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/bhuna-khichuri-with-beef-kosha.jpg', 'COMFORT CLASSIC', 'বৃষ্টি ও শীতের তৃপ্তি', false, true, 8),
  ('item-9', 'cat-veg', 'Heritage Panch Bhorta Platter', 'ঐতিহ্যবাহী ৫ পদের ভর্তা থালি', '৳২৫০', 'Assortment of Aloo, Begun, Chingri, Tomato, and Kalijira Bhortas mashed with raw mustard oil and fried chillies.', 'শিল-পাটায় বাটা আলু, পোড়া বেগুন, চিংড়ি, টমেটো ও কালিজিরা ভর্তার সাথে খাঁটি কাঁচা সরিষার তেল।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/heritage-panch-bhorta-platter.jpg', 'STONE GROUND', 'বাঙালির প্রাণের স্বাদ', false, true, 9),
  ('item-10', 'cat-biryani', 'Dhakai Shahi Morog Polao', 'ঢাকাই শাহী মোরগ পোলাও', '৳৪২০', 'Fragrant Kalijira rice served with spiced juicy quarter chicken, boiled egg, and sweet golden beresta.', 'গাওয়া ঘিয়ে ভাজা কালিজিরা চালের সুগন্ধি পোলাও এবং ঐতিহ্যবাহী কায়দায় রাঁধা মোরগের নরম মাংস।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/dhakai-shahi-morog-polao.jpg', 'BESTSELLER', 'আসল পোলাও', false, true, 10),
  ('item-11', 'cat-fish', 'Crispy Pan-Fried Silver Rupchanda', 'মচমচে রূপচাঁদা ফ্রাই', '৳৫৮০', 'Whole silver Pomfret marinated with fresh turmeric, red chili paste, and pan-fried crisp with onion relish.', 'কাঁচামরিচ, হলুদ ও লেবুর রসে মেখে কড়কড়ে ভাজা আস্ত রূপচাঁদা মাছ, সাথে পেঁয়াজ-মরিচ ভাঁজা।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/crispy-pan-fried-silver-rupchanda.jpg', 'CRISPY SEAFOOD', 'তাজা মাছ', false, true, 11),
  ('item-12', 'cat-starters', 'Special Crispy Fuchka Platter', 'স্পেশাল মুচমুচে ফুচকা প্লাটার', '৳১৬০', 'Handcrafted crispy puri shells stuffed with spiced yellow peas and served with spicy-sour tamarind water.', 'মুচমুচে পুরির ভেতরে ঝাল ডাবলি ঘুঘনি, ডিম কুচি আর জিভে জল আনা খাঁটি টক-মিষ্টি তেঁতুল জল।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/special-crispy-fuchka-platter.jpg', 'STREET SPECIAL', 'জিভে জল আনা', false, true, 12),
  ('item-13', 'cat-starters', 'Crispy Beguni & Piyaju Basket', 'মুচমুচে বেগুনী ও ডাল পেঁয়াজু', '৳১৪০', 'Thinly sliced eggplant and crunchy red lentil fritters spiced with carom seeds and rock salt.', 'মচমচে বেসনে ভাজা বেগুনী ও মুসুর ডালের গরম পেঁয়াজু—বিকেলের আড্ডার প্রিয় সঙ্গী।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/crispy-beguni-piyaju-basket.jpg', 'CRUNCHY', 'মুচমুচে স্ন্যাক্স', false, true, 13),
  ('item-14', 'cat-starters', 'Puran Dhaka Shami Kabab (2 Pcs)', 'পুরান ঢাকার স্পেশাল শামী কাবাব', '৳২০০', 'Melt-in-the-mouth minced beef patties cooked with chana dal, fresh mint, and whole roasted spices.', 'মিহি মাংসের কিমা ও ছোলার ডালের সাথে ভাজা জিরার মিশ্রণে তৈরি মুখে গলে যাওয়া শামী কাবাব।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/puran-dhaka-shami-kabab-2-pcs.jpg', 'HANDCRAFTED', 'কাবাব স্পেশাল', false, true, 14),
  ('item-15', 'cat-drinks', 'Shahi Dhakai Borhani', 'শাহী পুরান ঢাকার বোরহানি', '৳১৩০', 'Traditional spiced yogurt beverage blended with mint, coriander, roasted cumin, black salt, and green chilli.', 'টকদই, পুদিনা পাতা, বিট লবণ ও ভাজা জিরার মিশ্রণে তৈরি কাচ্চি বিরিয়ানির আসল ঢাকাই বোরহানি।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/shahi-dhakai-borhani.jpg', 'DIGESTIVE REFRESHER', 'খাঁটি বোরহানি', false, true, 15),
  ('item-16', 'cat-drinks', 'Pora Kancha Aamer Panna', 'পোড়া কাঁচা আমের পন্না শরবত', '৳১২০', 'Fire-roasted raw green mango pulp blended with pink salt, roasted cumin, and crushed ice.', 'আগুনে পোড়ানো কাঁচা আমের টক-মিষ্টি পাল্প, পুদিনা আর বরফ কুচিতে মন-প্রাণ জুড়ানো শরবত।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/pora-kancha-aamer-panna.jpg', 'CHILLED', 'প্রাণ জুড়ানো', false, true, 16),
  ('item-17', 'cat-desserts', 'Authentic Bogurar Sura Mishti Doi', 'ঐতিহ্যবাহী বগুড়ার সরা-দই', '৳১৭০', 'Authentic caramelized sweetened baked yogurt matured slowly in natural earthenware pots.', 'মাটির সরায় তৈরি বগুড়ার খাঁটি ঘন লাল মিষ্টি দই—ঘন সরের পরতে ভোজের রাজকীয় সমাপ্তি।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/authentic-bogurar-sura-mishti-doi.jpg', 'CLAY POT MATURED', 'বগুড়ার আসল দই', false, true, 17),
  ('item-18', 'cat-desserts', 'Shahi Zafrani Firni in Matir Patro', 'মাটির পাত্রে শাহী জাফরানি ফিরনি', '৳১৬০', 'Aromatic chinigura rice pudding cooked in thickened milk with Iranian saffron, pistachios, and silver leaf.', 'জাফরানের সোনালী আভা, কাঠবাদাম ও পেস্তা কুচিতে সাজানো মাটির সানকির সুস্বাদু ক্ষীর-ফিরনি।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/shahi-zafrani-firni-in-matir-patro.jpg', 'SAFFRON DESSERT', 'শাহী মিষ্টান্ন', false, true, 18),
  ('item-19', 'cat-desserts', 'Comillar Khas Rosomalai (2 Pcs)', 'কুমিল্লার স্পেশাল খাঁটি রসমলাই', '৳১৯০', 'Soft fresh cottage cheese dumplings simmered in luscious condensed cardamom milk.', 'তাজা ছানার নরম তুলতুলে রসগোল্লা আর এলাচের ঘ্রাণের ঘন ক্ষীরের তৈরি কুমিল্লার আসল রসমলাই।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/comillar-khas-rosomalai-2-pcs.jpg', 'SWEET MASTERPIECE', 'কুমিল্লার রসমলাই', false, true, 19),
  ('item-20', 'cat-desserts', 'Shahi Tukra with Malai Rabri', 'শাহী টুকরা ও মালাই রাবড়ি', '৳২০০', 'Ghee-crisped brioche soaked in saffron cardamom syrup, drenched with slow-reduced thick malai rabri.', 'ঘিয়ে ভাজা মুচমুচে টোস্টে জাফরানি রস ও ঘন দুধের মালাই রাবড়ির অতুলনীয় মোঘলাই মিষ্টি।', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/shahi-tukra-with-malai-rabri.jpg', 'ROYAL SWEET', 'মোঘলাই মিষ্টান্ন', false, true, 20)
on conflict (id) do nothing;

insert into gallery (id, url, title, bengali, aspect, sort_order, featured) values
  ('g1', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/dining-room.jpg', 'The Dining Room', 'শান্ত ও রুচিশীল সান্ধ্যকালীন আবহ', 'video', 1, true),
  ('g2', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/kitchen-cooking-process.jpg', 'Slow-Cooked Kacchi', 'দম কাচ্চির সুবাস ও জাফরানি চাল', 'portrait', 2, true),
  ('g3', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/exterior-signage-close-up.jpg', 'The Kansari Mark', 'কাঁসারীর ঐতিহ্যবাহী প্রতীক', 'square', 3, true),
  ('g5', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/spices.jpg', 'Artisanal Spices', 'শিল-পাটায় বাটা খাঁটি মসলার জাদু', 'video', 5, false),
  ('g6', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/hospitality-moment.jpg', 'Hospitality & Details', 'আন্তরিক সেবা ও যত্নশীল আতিথেয়তা', 'square', 6, false),
  ('g7', 'https://gdkqlzggyhzznomnmsvr.supabase.co/storage/v1/object/public/kansari-uploads/grand-kansari-thali.jpg', 'The Grand Kansari Thali', 'ঐতিহ্যবাহী কাঁসার পাত্রে পরিবেশন', 'square', 4, true)
on conflict (id) do nothing;

insert into reviews (id, name, text, date, rating, published, created_at) values
  ('r1', 'তাহসান রহমান (Tahsan Rahman)', 'কাচ্চি বিরিয়ানির মাংস এত তুলতুলে আর চালের সুবাস চমৎকার! ঢাকার ভেতরে খাঁটি বাংলাদেশি ঐতিহ্যবাহী খাবারের জন্য কাঁসারী অনন্য।', 'অক্টোবর ২০২৫', 5, true, now() - interval '20 days'),
  ('r2', 'নুসরাত জাহান (Nusrat Jahan)', 'কালাভুনা এবং সরিষা ইলিশ অসাধারণ লেগেছে। কাঁসার পাত্রে গরম গরম পরিবেশন আর পারিবারিক পরিবেশ মন কেড়ে নেওয়ার মতো।', 'সেপ্টেম্বর ২০২৫', 5, true, now() - interval '15 days'),
  ('r3', 'ইফতেখার আহমেদ (Iftekhar Ahmed)', 'পরিপাটি ও রুচিশীল ডাইনিং। প্রতিটি পদে খাঁটি স্বাদ ধরে রাখা হয়েছে। বিশেষ করে বিয়ের বাড়ির মোরগ পোলাও আর বোরহানি ছিল দারুণ।', 'নভেম্বর ২০২৫', 5, true, now() - interval '10 days'),
  ('r4', 'সাবরিনা চৌধুরী (Sabrina Chowdhury)', 'বগুড়ার দই আর জাফরানি ফিরনি দিয়ে ভোজ শেষ করার অনুভূতি ছিল অতুলনীয়। কর্মীদের ব্যবহারও অত্যন্ত আন্তরিক ও অমায়িক।', 'ডিসেম্বর ২০২৫', 5, true, now() - interval '5 days')
on conflict (id) do nothing;

insert into settings (id, data) values
  ('main', '{"name": "KANSARI", "bengaliName": "কাঁসারী", "tagline": "স্বাদের শিকড়। নতুন এক আয়োজন।", "englishTagline": "Authentic Bangali flavours, thoughtfully crafted.", "description": "মাটির কাছাকাছি খাঁটি বাংলাদেশি স্বাদ, আধুনিক পরিপাটি পরিবেশে—ঢাকার হৃদয়ে এক নতুন খাবারের অভিজ্ঞতা।", "englishDescription": "At Kansari, time-honoured Bangladeshi culinary traditions meet contemporary culinary finesse. Celebrating genuine heritage recipes in Dhaka.", "location": "Mohammadpur, Dhaka", "address": "House 14, Road 4, Ring Road\nMohammadpur, Dhaka 1207, Bangladesh", "phone": "+880 1740 527078", "whatsapp": "+880 1740 527078", "email": "contact@kansari.com", "socials": {"facebook": "https://facebook.com/kansaribd", "instagram": "https://instagram.com/kansari.dhaka"}, "openingHours": [{"day": "Saturday", "bengaliDay": "শনিবার", "isOpen": true, "openTime": "11:30 AM", "closeTime": "11:00 PM"}, {"day": "Sunday", "bengaliDay": "রবিবার", "isOpen": true, "openTime": "11:30 AM", "closeTime": "11:00 PM"}, {"day": "Monday", "bengaliDay": "সোমবার", "isOpen": true, "openTime": "11:30 AM", "closeTime": "11:00 PM"}, {"day": "Tuesday", "bengaliDay": "মঙ্গলবার", "isOpen": true, "openTime": "11:30 AM", "closeTime": "11:00 PM"}, {"day": "Wednesday", "bengaliDay": "বুধবার", "isOpen": true, "openTime": "11:30 AM", "closeTime": "11:00 PM"}, {"day": "Thursday", "bengaliDay": "বৃহস্পতিবার", "isOpen": true, "openTime": "11:30 AM", "closeTime": "11:00 PM"}, {"day": "Friday", "bengaliDay": "শুক্রবার", "isOpen": true, "openTime": "01:30 PM", "closeTime": "11:30 PM", "specialNote": "জুমার নামাজের পর শুরু"}], "content": {"heroHeadline": "An Authentic Bangladeshi Culinary Experience", "heroBengaliHeadline": "স্বাদের শিকড়। নতুন এক আয়োজন।", "heroSupportingText": "Dhaka''s premier destination for time-honoured heritage recipes cooked with pure artisanal spices.", "storyHeadline": "Roots, Fire & Heritage Brass", "storyBengaliHeadline": "কাঁসার পাত্রে ঐতিহ্যের সুবাস", "storyText": "In ancient Bengal, bell metal (কাঁসা) was not just tableware; it was a sacred canvas for hospitality. At Kansari, we revive these sacred culinary traditions.", "finalCtaHeading": "আপনার জন্য কাঁসার থালায় প্রস্তুত আমাদের আয়োজন।"}}'::jsonb)
on conflict (id) do nothing;

-- A couple of demo reservations so the admin dashboard doesn't look empty
insert into reservations (id, customer_name, phone, date, time, guests, notes, status, created_at, updated_at) values
  ('res-seed-1', 'কামরুল হাসান (Kamrul Hasan)', '+880 1712 345678', to_char(current_date, 'YYYY-MM-DD'), '19:30', 4, 'পরিবারের বিবাহবার্ষিকী উপলক্ষে জানালার পাশের টেবিল চাই।', 'CONFIRMED', now() - interval '2 hours', now() - interval '1 hour'),
  ('res-seed-2', 'ডাঃ সামিয়া রহমান (Dr. Samia)', '+880 1819 876543', to_char(current_date, 'YYYY-MM-DD'), '20:30', 6, 'কাচ্চি বিরিয়ানি ও বোরহানি অগ্রিম প্রস্তুত রাখার অনুরোধ।', 'PENDING', now() - interval '45 minutes', now() - interval '45 minutes'),
  ('res-seed-3', 'মাহমুদুল হক (Mahmudul Huq)', '+880 1911 223344', to_char(current_date + 1, 'YYYY-MM-DD'), '13:30', 2, 'শান্ত কোণায় টেবিল।', 'CONFIRMED', now() - interval '3 hours', now() - interval '2 hours 40 minutes')
on conflict (id) do nothing;
